import {
  HiOutlineHome,
  HiOutlineBriefcase,
  HiOutlineCalendar,
  HiOutlineClock,
  HiOutlineDocumentText,
  HiOutlineUserGroup,
  HiOutlineUsers,
  HiOutlineCurrencyDollar,
  HiOutlineBell,
  HiOutlineMenuAlt3,
  HiOutlineUserCircle,
  HiOutlineCog,
  HiOutlineFolder,
  HiOutlineX,
  HiOutlinePlus,
  HiOutlineSearch,
  HiOutlineEye,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineInformationCircle,
  HiOutlineExclamation,
  HiOutlineUpload,
  HiOutlineLink,
  HiOutlineTag,
  HiOutlineUser,
  HiOutlineUserRemove,
  HiOutlineClipboardList,
  HiOutlineDownload,
  HiOutlineAnnotation,
  HiOutlineCheckCircle,
  HiOutlineRefresh,
  HiOutlinePrinter,
  HiOutlineCreditCard,
  HiOutlineCash,
  HiOutlineReceiptTax,
  HiOutlineLogin,
  HiOutlineOfficeBuilding,
  HiOutlineCollection,
} from 'react-icons/hi'

const map = {
  home: HiOutlineHome,
  cases: HiOutlineCollection,
  sessions: HiOutlineBriefcase,
  appointments: HiOutlineCalendar,
  documents: HiOutlineDocumentText,
  lawyers: HiOutlineUserGroup,
  clients: HiOutlineUsers,
  companies: HiOutlineOfficeBuilding,
  invoices: HiOutlineCurrencyDollar,
  bell: HiOutlineBell,
  menu: HiOutlineMenuAlt3,
  close: HiOutlineX,
  user: HiOutlineUserCircle,
  cog: HiOutlineCog,
  folder: HiOutlineFolder,
  clock: HiOutlineClock,
  calendar: HiOutlineCalendar,
  plus: HiOutlinePlus,
  search: HiOutlineSearch,
  eye: HiOutlineEye,
  edit: HiOutlinePencil,
  trash: HiOutlineTrash,
  info: HiOutlineInformationCircle,
  alert: HiOutlineExclamation,
  upload: HiOutlineUpload,
  link: HiOutlineLink,
  tag: HiOutlineTag,
  person: HiOutlineUser,
  opponent: HiOutlineUserRemove,
  notes: HiOutlineClipboardList,
  download: HiOutlineDownload,
  annotation: HiOutlineAnnotation,
  check: HiOutlineCheckCircle,
  calendarCheck: HiOutlineCheckCircle,
  refresh: HiOutlineRefresh,
  print: HiOutlinePrinter,
  payment: HiOutlineCreditCard,
  cash: HiOutlineCash,
  receipt: HiOutlineReceiptTax,
  login: HiOutlineLogin,
}

export function Icon({ name, className, size }) {
  const Cmp = map[name] || HiOutlineHome
  return <Cmp className={className} size={size} aria-hidden />
}
